/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#131313",
        "on-tertiary": "#00344e",
        "on-tertiary-container": "#ffffff",
        "on-primary": "#690007",
        "inverse-surface": "#e2e2e2",
        "error-container": "#93000a",
        "on-surface-variant": "#e7bdb8",
        "on-secondary-fixed": "#410002",
        "inverse-on-surface": "#303030",
        "surface-tint": "#ffb4ac",
        "tertiary": "#8aceff",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#004b6f",
        "error": "#ffb4ab",
        "surface-variant": "#353535",
        "on-primary-fixed": "#410002",
        "primary-fixed-dim": "#ffb4ac",
        "surface-container": "#1f1f1f",
        "tertiary-fixed": "#c9e6ff",
        "primary-container": "#e82127",
        "surface-container-highest": "#353535",
        "outline": "#ae8884",
        "on-background": "#e2e2e2",
        "secondary-fixed-dim": "#ffb4ac",
        "surface-container-low": "#1b1b1b",
        "surface-bright": "#393939",
        "on-surface": "#e2e2e2",
        "on-error": "#690005",
        "secondary-container": "#8e1c1b",
        "on-secondary-container": "#ff9f95",
        "primary-fixed": "#ffdad6",
        "on-primary-fixed-variant": "#93000e",
        "inverse-primary": "#c00015",
        "tertiary-fixed-dim": "#8aceff",
        "surface": "#131313",
        "on-tertiary-fixed": "#001e2f",
        "tertiary-container": "#007eb5",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#8a1a19",
        "outline-variant": "#5d3f3c",
        "secondary-fixed": "#ffdad6",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#140000",
        "on-error-container": "#ffdad6",
        "secondary": "#ffb4ac",
        "primary": "#ffb4ac",
        "on-secondary": "#690007"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
};
